### ISSUE TITLE
emit transaction failed

### ISSUE THREAD

**Issue by mrfreezer** [yuku-t/fluent-plugin-mysqlslowquery#8]
using version 0.0.5 and i am getting  the following error:

2015-04-09 13:38:22 +0200 [warn]: emit transaction failed: error_class=TypeError error="no implicit conversion of Symbol into String" tag="mysqld.slowquery"
  2015-04-09 13:38:22 +0200 [warn]: /etc/td-agent/plugin/out_gelf.rb:72:in `+'
  2015-04-09 13:38:22 +0200 [warn]: /etc/td-agent/plugin/out_gelf.rb:72:in `block in format'
  2015-04-09 13:38:22 +0200 [warn]: /etc/td-agent/plugin/out_gelf.rb:39:in `each_pair'
  2015-04-09 13:38:22 +0200 [warn]: /etc/td-agent/plugin/out_gelf.rb:39:in `format'
  2015-04-09 13:38:22 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/output.rb:265:in `block in format_stream'
  2015-04-09 13:38:22 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/event.rb:128:in `call'
  2015-04-09 13:38:22 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/event.rb:128:in `block in each'
  2015-04-09 13:38:22 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/event.rb:127:in `each'
  2015-04-09 13:38:22 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/event.rb:127:in `each'
  2015-04-09 13:38:22 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/output.rb:264:in `format_stream'
  2015-04-09 13:38:22 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/output.rb:250:in `emit'
  2015-04-09 13:38:22 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/event_router.rb:88:in `emit_stream'
  2015-04-09 13:38:22 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/engine.rb:116:in `emit_stream'
  2015-04-09 13:38:22 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-mysqlslowquery-0.0.5/lib/fluent/plugin/in_mysql_slow_query.rb:60:in `receive_lines'
  2015-04-09 13:38:22 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:1036:in `call'
  2015-04-09 13:38:22 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:1036:in `on_notify'
  2015-04-09 13:38:22 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:860:in `on_notify'
  2015-04-09 13:38:22 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:971:in `call'
  2015-04-09 13:38:22 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:971:in `on_change'
  2015-04-09 13:38:22 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.3.0/lib/cool.io/loop.rb:88:in `run_once'
  2015-04-09 13:38:22 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.3.0/lib/cool.io/loop.rb:88:in `run'
  2015-04-09 13:38:22 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:773:in `run'

anyone got any ideas on it? 
output is, if that's of any interest, the gelf output since i am forwarding this into graylog.

**Comment by mrfreezer** [comment]
oh and thats my fluentd-config:

<source>
  type mysql_slow_query
  path /var/log/mysql/slow-queries.log
  pos_file /var/log/td-agent/mysql-slow-queries.log.pos
  tag mysqld.slowquery
</source>

nothing special i suppose :(
